# Generated by Django 3.1.2 on 2020-10-20 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noTarjeta', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('hora', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('cuidad', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('entreCalles', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProductos', models.CharField(max_length=30)),
                ('cantidadProductos', models.CharField(max_length=30)),
                ('precioProductos', models.CharField(max_length=30)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFC', models.CharField(max_length=30)),
                ('razonSocial', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('correo', models.EmailField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=30)),
                ('colonia', models.CharField(max_length=50)),
                ('cuidad', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('entreCalles', models.CharField(max_length=50)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.compra')),
            ],
        ),
    ]
