# Generated by Django 3.1.2 on 2020-10-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cantidadProductos',
            new_name='cantidadProducto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='codigoProductos',
            new_name='codigoProducto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='precioProductos',
            new_name='precioProducto',
        ),
    ]
