# Generated by Django 3.1.2 on 2020-11-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201117_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='noTarjeta',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
