# Generated by Django 3.1.2 on 2020-10-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_compra_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='cuidad',
            new_name='ciudad',
        ),
    ]
