# Generated by Django 3.1.2 on 2020-10-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201028_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='cuidad',
            new_name='ciudad',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
