# Generated by Django 3.1.2 on 2020-10-20 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePila', models.CharField(max_length=30)),
                ('apellidoPat', models.CharField(max_length=30)),
                ('apellidoMat', models.CharField(max_length=30)),
                ('fechaNac', models.DateField()),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=30, null=True)),
                ('correo', models.EmailField(max_length=30, null=True)),
                ('calle', models.CharField(max_length=50, null=True)),
                ('colonia', models.CharField(max_length=50, null=True)),
                ('cuidad', models.CharField(max_length=50, null=True)),
                ('cp', models.CharField(max_length=10, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('entreCalles', models.CharField(max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProductos', models.CharField(max_length=30)),
                ('cantidadProductos', models.CharField(max_length=30)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.carrito')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.cliente'),
        ),
    ]
