# Generated by Django 3.1.2 on 2020-11-14 00:52

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePila', models.CharField(max_length=30)),
                ('apellidoPat', models.CharField(max_length=30)),
                ('apellidoMat', models.CharField(max_length=30)),
                ('fechaNac', models.DateField()),
                ('genero', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NameException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Exceptions',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.cliente')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': '-fecha',
            },
        ),
        migrations.CreateModel(
            name='ClienteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=12, null=True, region=None)),
                ('correo', models.EmailField(blank=True, default='', max_length=30, null=True)),
                ('calle', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('colonia', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('cp', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('estado', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('entreCalles', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienteInfo', to='clients.cliente')),
            ],
            options={
                'verbose_name_plural': 'Clientes Info',
            },
        ),
        migrations.CreateModel(
            name='CarritoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=30)),
                ('cantidadProducto', models.CharField(max_length=30)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritoInfo', to='clients.carrito')),
            ],
            options={
                'verbose_name_plural': 'Carritos Info',
            },
        ),
    ]
