# Generated by Django 3.1.2 on 2020-11-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('colonia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(max_length=1),
        ),
    ]
