# Generated by Django 3.1.2 on 2020-10-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritoinfo',
            options={'verbose_name_plural': 'Carritos Info'},
        ),
        migrations.AlterModelOptions(
            name='clienteinfo',
            options={'verbose_name_plural': 'Clientes Info'},
        ),
    ]
