# Generated by Django 3.1.2 on 2020-11-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exceptions',
            new_name='NameException',
        ),
        migrations.AlterModelOptions(
            name='nameexception',
            options={'verbose_name_plural': 'Exceptions'},
        ),
    ]
