# Generated by Django 3.1.2 on 2020-11-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20201117_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritoinfo',
            options={'verbose_name_plural': 'Carritos_Info'},
        ),
        migrations.AlterModelOptions(
            name='clienteinfo',
            options={'verbose_name_plural': 'Clientes_Info'},
        ),
        migrations.AlterModelOptions(
            name='codigopostal',
            options={'ordering': ['id'], 'verbose_name_plural': 'Codigos postales'},
        ),
        migrations.AlterModelOptions(
            name='nameexception',
            options={'verbose_name_plural': 'Excepciones'},
        ),
        migrations.AddField(
            model_name='clienteinfo',
            name='anioTarjeta',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clienteinfo',
            name='mesTarjeta',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='clienteinfo',
            name='noTarjeta',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
