# Generated by Django 3.1.2 on 2020-11-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20201112_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='created',
            new_name='created_date',
        ),
    ]
