# Generated by Django 3.1.2 on 2020-10-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20201019_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteinfo',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
