# Generated by Django 3.1.2 on 2020-10-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clienteinfo_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
