# Generated by Django 3.1.2 on 2020-11-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20201113_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteinfo',
            old_name='cuidad',
            new_name='ciudad',
        ),
    ]
