# Generated by Django 3.1.2 on 2020-10-25 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20201025_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
