# Generated by Django 3.1.2 on 2020-10-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_cliente_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'get_latest_by': '-fecha'},
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='calle',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='colonia',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='correo',
            field=models.EmailField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='cp',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='cuidad',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='entreCalles',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='estado',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='telefono',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
