# Generated by Django 3.1.2 on 2020-10-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20201028_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritoinfo',
            old_name='cantidadProductos',
            new_name='cantidadProducto',
        ),
        migrations.RenameField(
            model_name='carritoinfo',
            old_name='codigoProductos',
            new_name='codigoProducto',
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='colonia',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='cp',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='cuidad',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='entreCalles',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
