# Generated by Django 3.1.2 on 2020-10-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20201028_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoinfo',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritoInfo', to='clients.carrito'),
        ),
    ]
