# Generated by Django 3.1.2 on 2020-11-10 21:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_cliente_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='clienteinfo',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=12, null=True, region=None),
        ),
    ]
